version: '3'
services:
    app:
        build: .
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: postgres
            POSTGRES_DB: todo
            POSTGRES_HOST: vultr_db_1,
        ports:
            - 3000:3000

    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: password
        ports:
            - 5432:5432