version: '3'
services:
    app:
        build: .
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: todo
        ports:
            - "80:3000"

    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: password
        ports:
            - 5432:5432